// lib/constants/locations.ts
export const LOCATIONS = [
  { city: 'Austin', state: 'TX', population: 961855 },
  { city: 'Miami', state: 'FL', population: 442241 },
  { city: 'Seattle', state: 'WA', population: 737015 },
  { city: 'Chicago', state: 'IL', population: 2746388 },
  { city: 'Denver', state: 'CO', population: 715522 },
  { city: 'Phoenix', state: 'AZ', population: 1608139 },
  { city: 'Los Angeles', state: 'CA', population: 3898747 },
  { city: 'New York', state: 'NY', population: 8804190 },
  { city: 'Houston', state: 'TX', population: 2304580 },
  { city: 'Dallas', state: 'TX', population: 1304379 },
  { city: 'San Diego', state: 'CA', population: 1386932 },
  { city: 'San Jose', state: 'CA', population: 1013240 },
  { city: 'San Francisco', state: 'CA', population: 873965 },
  { city: 'Boston', state: 'MA', population: 675647 },
  { city: 'Atlanta', state: 'GA', population: 498715 },
  { city: 'Portland', state: 'OR', population: 652503 },
  { city: 'Las Vegas', state: 'NV', population: 641903 },
  { city: 'Orlando', state: 'FL', population: 307573 },
  { city: 'Nashville', state: 'TN', population: 689447 },
  { city: 'Charlotte', state: 'NC', population: 874579 }
];

export const STATES = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' }
];